#!/usr/bin/env bash

{ # this ensures the entire script is downloaded #

shopt -s extglob
set -o errtrace
set -o errexit
set -o pipefail


log()  { printf "%b\n" "$*"; }
debug(){ [[ ${rvm_debug_flag:-0} -eq 0 ]] || printf "%b\n" "$*" >&2; }
warn() { log "WARN: $*" >&2 ; }
fail() { fail_with_code 1 "$*" ; }
fail_with_code() { code="$1" ; shift ; log "\nERROR: $*\n" >&2 ; exit "$code" ; }

# Check and Install all dependencies
function install_dependencies_linux() {
    echo "Installing dependencies for $OSTYPE"

    if [ -f /etc/lsb-release ]; then
        sudo apt update --yes
        sudo apt install --yes git
        sudo apt install --yes software-properties-common
        sudo add-apt-repository --yes --update ppa:ansible/ansible
        sudo apt install --yes ansible
    else
        fail_with_code 1 "Installation is not support for your distribution"
    fi
}

if [[ "$OSTYPE" == "linux-gnu" ]]; then
    install_dependencies_linux
else
    fail_with_code 1 "Installation is not supported for your platform $OS"
fi

mkdir -p ${HOME}/projects/repos/personal && cd "$_"
if ! [[ -d "${HOME}/projects/repos/personal/bootstrap" ]];
then
    git clone https://github.com/acodefella/bootstrap.git
fi

cd bootstrap
ansible-playbook \
    --inventory="locahost," \
    --connection=local      \
    playbook.yml

} # this ensures the entire script is downloaded #
